import React from "react";
import {
  // Only the most essential icons that actually exist in Heroicons
  HomeIcon,
  MagnifyingGlassIcon as SearchIcon,
  BellIcon,
  UserIcon,
  UsersIcon,
  Cog6ToothIcon as SettingsIcon,
  PencilIcon as EditIcon,
  TrashIcon as DeleteIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  XMarkIcon as CrossIcon,
  EyeIcon,
  EyeSlashIcon as EyeCloseIcon,
  ArrowDownTrayIcon as DownloadIcon,
  ArrowUpTrayIcon as UploadIcon,
  ShareIcon,
  HeartIcon,
  StarIcon,
  CalendarIcon,
  ClockIcon,
  MapPinIcon as LocationIcon,
  PhoneIcon,
  EnvelopeIcon as MailIcon,
  LockClosedIcon as LockIcon,
  KeyIcon,
  SignalIcon as WifiIcon,
  ChartBarIcon as BarChartIcon,
  ChartPieIcon as PieChartIcon,
  CurrencyDollarIcon as DollarIcon,
  BuildingLibraryIcon as BankIcon,
  CreditCardIcon,
  InformationCircleIcon as InfoIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ExclamationTriangleIcon as WarningIcon,
  CheckCircleIcon,
  XCircleIcon,
  PlusCircleIcon,
  MinusCircleIcon,
  PauseCircleIcon,
  PlayIcon,
  StopIcon,
  UserCircleIcon,
  UserGroupIcon,
  DocumentIcon,
  FolderIcon,
  PaperClipIcon,
  PhotoIcon,
  CameraIcon,
  FilmIcon,
  PaintBrushIcon,
  ScissorsIcon,
  WrenchIcon,
  BoltIcon,
  FireIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  SparklesIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  FaceSmileIcon,
  FaceFrownIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  PhoneArrowUpRightIcon,
  PhoneArrowDownLeftIcon,
  PhoneXMarkIcon,
  VideoCameraIcon,
  VideoCameraSlashIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  PrinterIcon,
  ServerIcon as DatabaseIcon, // Use ServerIcon as DatabaseIcon fallback
  CpuChipIcon,
  Bars3Icon,
  Bars4Icon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3Icon as Bars3CenterRightIcon, // Use Bars3Icon as fallback for Bars3CenterRightIcon
} from "@heroicons/react/24/outline";

// Re-export commonly used icons with consistent naming
export {
  HomeIcon,
  SearchIcon,
  BellIcon,
  UserIcon,
  UsersIcon,
  SettingsIcon,
  EditIcon,
  DeleteIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  CrossIcon,
  EyeIcon,
  EyeCloseIcon,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  HeartIcon,
  StarIcon,
  CalendarIcon,
  ClockIcon,
  LocationIcon,
  PhoneIcon,
  MailIcon,
  LockIcon,
  KeyIcon,
  WifiIcon,
  BarChartIcon,
  PieChartIcon,
  DollarIcon,
  BankIcon,
  CreditCardIcon,
  InfoIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  WarningIcon,
  CheckCircleIcon,
  XCircleIcon,
  PlusCircleIcon,
  MinusCircleIcon,
  PauseCircleIcon,
  PlayIcon,
  StopIcon,
  UserCircleIcon,
  UserGroupIcon,
  DocumentIcon,
  FolderIcon,
  PaperClipIcon,
  PhotoIcon,
  CameraIcon,
  FilmIcon,
  PaintBrushIcon,
  ScissorsIcon,
  WrenchIcon,
  BoltIcon,
  FireIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  SparklesIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  FaceSmileIcon,
  FaceFrownIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  PhoneArrowUpRightIcon,
  PhoneArrowDownLeftIcon,
  PhoneXMarkIcon,
  VideoCameraIcon,
  VideoCameraSlashIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  PrinterIcon,
  DatabaseIcon, // Export DatabaseIcon (aliased from ServerIcon)
  CpuChipIcon,
  Bars3Icon,
  Bars4Icon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3CenterRightIcon, // Export Bars3CenterRightIcon (aliased from Bars3Icon)
};

// Default export for easy importing
export default {
  HomeIcon,
  SearchIcon,
  BellIcon,
  UserIcon,
  UsersIcon,
  SettingsIcon,
  EditIcon,
  DeleteIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  CrossIcon,
  EyeIcon,
  EyeCloseIcon,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  HeartIcon,
  StarIcon,
  CalendarIcon,
  ClockIcon,
  LocationIcon,
  PhoneIcon,
  MailIcon,
  LockIcon,
  KeyIcon,
  WifiIcon,
  BarChartIcon,
  PieChartIcon,
  DollarIcon,
  BankIcon,
  CreditCardIcon,
  InfoIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  WarningIcon,
  CheckCircleIcon,
  XCircleIcon,
  PlusCircleIcon,
  MinusCircleIcon,
  PauseCircleIcon,
  PlayIcon,
  StopIcon,
  UserCircleIcon,
  UserGroupIcon,
  DocumentIcon,
  FolderIcon,
  PaperClipIcon,
  PhotoIcon,
  CameraIcon,
  FilmIcon,
  PaintBrushIcon,
  ScissorsIcon,
  WrenchIcon,
  BoltIcon,
  FireIcon,
  SunIcon,
  MoonIcon,
  CloudIcon,
  SparklesIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  FaceSmileIcon,
  FaceFrownIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  PhoneArrowUpRightIcon,
  PhoneArrowDownLeftIcon,
  PhoneXMarkIcon,
  VideoCameraIcon,
  VideoCameraSlashIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  PrinterIcon,
  DatabaseIcon,
  CpuChipIcon,
  Bars3Icon,
  Bars4Icon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3CenterRightIcon,
};
