import { useGetRevenueByChallengesQuery } from "@/store/api/challenges/challenges-api";
import type { TGetRevenueByChallengesArgs } from "@/store/api/challenges/challenges.types";
import type { TTimeRange } from "@/store/api/common-api-types";
import ApexAreaChart from "@/components/charts/apex-area-chart";
import LegendButton from "@/components/charts/LegendButton";
import RenderData from "@/components/render-data";
import AreaChartSkeleton from "@/components/skeleton/area-chart-skeleton";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

import type { TDateRange } from "./overview-content";

function ChallengesRevenueChart({
  dateRange,
  activeTime,
}: {
  dateRange: TDateRange;
  activeTime: TTimeRange;
}) {
  const revenueArgs: TGetRevenueByChallengesArgs = {
    filterType:
      activeTime === "custom" || activeTime === "all" ? undefined : activeTime,
    startDate: activeTime === "custom" ? dateRange.from : undefined,
    endDate: activeTime === "custom" ? dateRange.to : undefined,
  };
  const { data: getRevenueByChallengesRes, ...getRevenueByChallengesApiState } =
    useGetRevenueByChallengesQuery(revenueArgs);

  const getRevenueByChallengesData = getRevenueByChallengesRes?.data;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle>Revenue Generated by Challenges</CardTitle>
          <LegendButton />
        </div>
      </CardHeader>
      <CardContent>
        <RenderData
          data={getRevenueByChallengesData}
          expectedDataType="object"
          {...getRevenueByChallengesApiState}
          loadingSkeleton={<AreaChartSkeleton />}
        >
          <ApexAreaChart
            categories={getRevenueByChallengesData?.categories || []}
            series={[
              {
                name: "Revenue",
                data: getRevenueByChallengesData?.series[0]?.data || [],
              },
            ]}
            height={250}
            colors={["#F79009", "#17B26A", "#F04438"]}
          />
        </RenderData>
      </CardContent>
    </Card>
  );
}

export default ChallengesRevenueChart;
